### ISSUE TITLE
Include Baraffe tracks into Mors?

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/MORS#5]
Currently there are three ways to get the stellar flux in Proteus:
- first one (Legacy way) is the one used in Janus. It interpolates data stored in a "luminosity track" file.
- second one is the actual Mors using Spada data.
- third one uses the Baraffe tracks and is implemented into Proteus (utils/baraffe.py, following previous work of Harrison).

It would make sense to gather all these options into Mors so that this package handles all the stellar physics. We make then Janus, Zephyrus and Proteus dependent of Mors.

Beforehand, I would like to discuss:
- @nichollsh, you mention in a previous comment you would prefer to have a separate package to handle the Baraffe track. At first glance, it seems to me it will create additional complexity. But is there a specific reason for not merging everything together?
- If I am not mistaken, it seems the luminosity data in Janus are actually an extraction of the Baraffe data. If this is correct, I do not get the difference between the BaraffeSolarConstant function in Proteus and the InterpolateStellarLuminosity in Janus.
Could you clarify this maybe @timlichtenberg?

**Comment by lsoucasse** [comment]
I have double checked and I confirm the data in Janus files Lum_mxx.txt are identical to the data in the Baraffe track file (after log conversion of the age and and L/Ls columns).

**Comment by nichollsh** [comment]
Good to hear that they are indeed the same data, since then we can remove one of them.

My main reason for wanting the Baraffe tracks separate was that it would be useful to have a wrapper for them only. This would be without all the extra modelling that comes with MORS in terms of rotation and per-band scalings. This would provide a useful "external" benchmark for MORS. Also, I think that having smaller modules is better and embraces the modular philosophy that we are going for.

Creating a small package for reading-in and interpolating the tracks would be quite simple, I think. The main disadvantage with this would be duplicating some code contained in MORS relating to reading and writing spectra.

I don't think integrating the Baraffe tracks into MORS would (easily) provide additional utility beyond that described above. The way that MORS parses the Spada tracks seems very complex, as it compiles them into a pickle file at first run. Doing this also with the Baraffe tracks seems quite tricky.

**Comment by nichollsh** [comment]
However, this isn't a point that I will insist upon. I am open to the possibility of including the Baraffe tracks in MORS if it would add additional useful functionality/physics.

**Comment by lsoucasse** [comment]
Thank you for your feedback @nichollsh.

My idea was to add these Baraffe functions into Mors without looking for compatibility/consistency with actual Mors functions (just as additional separate functions). We can still make an internal benchmark (for the total luminosity I suppose) Spada vs Baraffe and create a corresponding test. But I agree there is not much logic for the package itself if there is no interaction with the rest of Mors's functionalities. I suggest to move Baraffe functions into Mors for the time being and later see whether we split the two models or we go for more integration.

So now we have to functions to compute total luminosity from Baraffe data:
- InterpolateStellarLuminosity in Janus which does actual interpolation;
- BaraffeSolarConstant in Proteus which does first an log-interpolation of the whole track into a fine temporal grid, and then take the nearest neighbour (fastest option).
Shall we get rid of one of these two options, maybe the InterpolateStellarLuminosity? Or we keep both for backward compatibility?

**Comment by nichollsh** [comment]
This makes sense to me. Moving the Baraffe tracks into MORS at least is better than having them in PROTEUS directly. Later on, we can discuss what to do with the data from there.

I agree that we should get rid of one of the two Baraffe sets. Doing 2D interpolation probably makes the most sense. @lsoucasse, do they produce the same results when plotted at locations "between" the tracks?

**Comment by lsoucasse** [comment]
Hi @nichollsh, the two routines will give different results between tracks anyway because they use different interpolation methods (linear or log-linear). I can check they give (hopefully) similar results but will be hard to say which is the best.

In Janus, there is 2D interpolation (mass and time) while there is only time interpolation in Proteus. I agree we need 2D interpolation.
